spring:
  application:
    name: config-server
  datasource:
    url: jdbc:mysql://employee.cpfqfe4an5gg.us-east-1.rds.amazonaws.com/employee
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
